--ASSIGNMENT: MOVIE TICKET BOOKING SYSTEM
BEGIN TRANSACTION;

CREATE TABLE BOOKINGS(
BOOKINGID INT PRIMARY KEY,
CUSTOMERNAME VARCHAR(60),
MOVIENAME VARCHAR(60),
SEATSBOOKED INT,
TOTALPRICE INT,
);

DROP TABLE BOOKINGS;

SELECT * FROM BOOKINGS;

INSERT INTO BOOKINGS(BOOKINGID, CUSTOMERNAME, MOVIENAME, SEATSBOOKED, TOTALPRICE) VALUES (111, 'JOHN', 'CHHAVA', 12, 400);
INSERT INTO BOOKINGS(BOOKINGID, CUSTOMERNAME, MOVIENAME, SEATSBOOKED, TOTALPRICE) VALUES (112, 'SAM', 'CHHAVA',44,  400);
INSERT INTO BOOKINGS(BOOKINGID, CUSTOMERNAME, MOVIENAME, SEATSBOOKED, TOTALPRICE) VALUES (113, 'NICK', 'CHHAVA', 48, 400);
INSERT INTO BOOKINGS(BOOKINGID, CUSTOMERNAME, MOVIENAME, SEATSBOOKED, TOTALPRICE) VALUES (114, 'ROSY', 'CHHAVA', 47, 400);

SAVE TRANSACTION SVPT;

ALTER TABLE BOOKINGS ALTER COLUMN SEATSBOOKED INT;

DELETE FROM BOOKINGS WHERE BOOKINGID=113;
DELETE FROM BOOKINGS WHERE BOOKINGID=112;

ROLLBACK TRANSACTION SVPT;

COMMIT;
