--DQL ASSIGNMENT
--HOSPITAL MANAGEMENT SYSTEM

CREATE TABLE PATIENT(
PATIENTID INT IDENTITY(101,1) PRIMARY KEY
);

ALTER TABLE PATIENT ADD PNAME VARCHAR(60), AGE INT, DISEASE VARCHAR(60), DOCTORASSIGNED VARCHAR(60);

SELECT * FROM PATIENT;

INSERT INTO PATIENT(PNAME, AGE, DISEASE , DOCTORASSIGNED) VALUES ('RASHMI', 56, 'FEVER', 'ISHANI');
INSERT INTO PATIENT(PNAME, AGE, DISEASE , DOCTORASSIGNED) VALUES ('KAMYA', 69, 'FEVER', 'ISHANI');
INSERT INTO PATIENT(PNAME, AGE, DISEASE , DOCTORASSIGNED) VALUES ('HEENA', 88, 'CHICKENPOX', 'RAMYA');
INSERT INTO PATIENT(PNAME, AGE, DISEASE , DOCTORASSIGNED) VALUES ('SIDHARDH', 45, 'FEVER', 'NEHA');
INSERT INTO PATIENT(PNAME, AGE, DISEASE , DOCTORASSIGNED) VALUES ('RUHI', 22, 'COUGH', 'SACHI');

--NAMES OF PATIENTS ABOVE 60 YEARS
SELECT * FROM PATIENT WHERE AGE>60;

--PATIENT ASSIGNED TO SPECIFIC DOCTOR
SELECT * FROM PATIENT WHERE DOCTORASSIGNED='NEHA';

--COUNT OF PATIENTS PER DISEASE
SELECT DISEASE, COUNT(DISEASE) FROM PATIENT GROUP BY DISEASE;
