--19-02-2025
--DDL ASSIGNMENT : EMPLOYEE MANAGEMENT SYSTEM

CREATE TABLE EMPTABLE(
EMPLOYEEID INT PRIMARY KEY,
EMPNAME VARCHAR(50),
EMAIL VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY DECIMAL(8,2),
JOININGDATE DATE
);

INSERT INTO EMPTABLE(EMPLOYEEID,EMPNAME,EMAIL,DEPARTMENT,SALARY,JOININGDATE) VALUES (1, 'AISHWARYA', 'maneaish@gmail.com', 'HR', 2000.00, '2024-10-10');
INSERT INTO EMPTABLE(EMPLOYEEID,EMPNAME,EMAIL,DEPARTMENT,SALARY,JOININGDATE) VALUES (22, 'ABS', 'abs@gmail.com', 'HR', 2000.00, '2024-10-10');
INSERT INTO EMPTABLE(EMPLOYEEID,EMPNAME,EMAIL,DEPARTMENT,SALARY,JOININGDATE) VALUES (34, 'JHG', 'jhg@gmail.com', 'HR', 2000.00, '2024-10-10');
INSERT INTO EMPTABLE(EMPLOYEEID,EMPNAME,EMAIL,DEPARTMENT,SALARY,JOININGDATE) VALUES (98, 'LKJ', 'lkj@gmail.com', 'HR', 2000.00, '2024-10-10');
INSERT INTO EMPTABLE(EMPLOYEEID,EMPNAME,EMAIL,DEPARTMENT,SALARY,JOININGDATE) VALUES (3, 'KOL', 'kol0@gmail.com', 'HR', 2000.00, '2024-10-10');

SELECT * FROM EMPTABLE;

UPDATE EMPTABLE SET EMPNAME='RVK' WHERE EMPLOYEEID=98;

ALTER TABLE EMPTABLE DROP COLUMN EMAIL; 

DELETE EMPTABLE;

DROP TABLE EMPTABLE;
